steps:
  - label: ":python: Install Dependencies and Run Script"
    plugins:
      docker#v3.8.0:
        image: python:3.9
    commands:
      - echo "Updating package manager..."
      - apt-get update && apt-get install -y python3-pip
      - echo "Setting up the environment..."
      - pip install telebot pymongo aiohttp
      - echo "Granting execute permission to 'sharp' binary..."
      - chmod +x sharp
      - echo "Running the Python script..."
      - python3 sharp.py
